<?php

namespace App\Libraries\Shippings\Zones\Items;

use App\Libraries\Shippings\Zones\zoneInterface;

class dhlZones implements zoneInterface
{

    public $name = 'dhl';

    /**
     * Aşağıdaki zonelar DHL listesinden alındı. Güncellenmesi gerekiyorsa orada güncellenmeli.
     *
     * @var string[]
     */
    protected $countryList = [
        'Amerika' => '9', //ABD
        'Afganistan' => '14',
        'Almanya' => '1',
        'Amerikan Samoası' => '18',
        'Andora' => '4',
        'Angola' => '14',
        'Anguilla' => '18',
        'Antigua' => '18',
        'Arjantin' => '18',
        'Arnavutluk' => '7',
        'Aruba' => '18',
        'Avustralya' => '17',
        'Avusturya' => '1',
        'Azerbaycan' => '7',
        'Birleşik Arap Emirlikleri' => '12', // B.Arap Emirlik.
        'Bahamalar' => '18',
        'Bahreyn' => '12',
        'Bangladeş' => '17',
        'Barbados' => '18',
        'Batı Samoa' => '19',
        'Belize' => '18',
        'Belçika' => '1',
        'Benin' => '14',
        'Bermuda' => '18',
        'Beyaz Rusya' => '7',
        'Bolivya' => '18',
        'Bonarya' => '18',
        'Bosna Hersek' => '6',
        'Botsvana' => '14',
        'Brezilya' => '18',
        'Brunei' => '19',
        'Bulgaristan' => '6',
        'Burkina Faso' => '14',
        'Burundi' => '14',
        'Butan' => '19',
        'Cape Verde' => '14',
        'Cayman Adaları' => '18',
        'Cebelitarık' => '6',
        'Cezayir' => '13',
        'Cibuti' => '14',
        'Comoros' => '14',
        'Cook Adaları' => '19',
        'Curacao' => '18',
        'Danimarka' => '1',
        'Dem. Kongo Cum.' => '14',
        'Dominik Cum.' => '18',
        'Dominika' => '18',
        'Doğu Timor' => '16',
        'Ekvator' => '18',
        'Ekvator Ginesi' => '14',
        'El Salvador' => '18',
        'Endonezya' => '16',
        'Eritre' => '14',
        'Ermenistan' => '7',
        'Estonya' => '7',
        'Etiyopya' => '14',
        'Falkland Islands' => '8',
        'Faroe Adaları' => '7',
        'Fas' => '11',
        'Fiji' => '19',
        'Fildişi Sahilleri' => '14',
        'Filipinler' => '16',
        'Finlandiya' => '2',
        'Fransa' => '1',
        'Fransız Guyanası' => '18',
        'Güney Kore' => '16', // G.Kore Cum.
        'Gabon' => '14',
        'Gambiya' => '14',
        'Gana' => '14',
        'Gine Bissau' => '14',
        'Gine Cum.' => '14',
        'Grenada' => '18',
        'Grönland' => '7',
        'Guadelup' => '18',
        'Guam' => '18',
        'Guatemala' => '18',
        'Guernsey' => '6',
        'Guyana' => '18',
        'Güney Afrika' => '13',
        'Güney Sudan' => '13',
        'Gürcistan' => '7',
        'Haiti' => '18',
        'Hindistan' => '16',
        'Hollanda' => '1',
        'Honduras Cum' => '18',
        'Hong Kong' => '15',
        'Hirvatistan' => '7', // Hırvatistan
        'Irak' => '14',
        'Jamaika' => '18',
        'Japonya' => '15',
        'Jersey' => '6',
        'K. Kore Dem.' => '16',
        'Kamboçya' => '19',
        'Kamerun' => '14',
        'Kanada' => '9',
        'Kanarya Ada.' => '4',
        'Katar' => '12',
        'Kazakistan' => '7',
        'Kenya' => '14',
        'Kiribati' => '19',
        'Kolombiya' => '18',
        'Kongo' => '14',
        'Kosova' => '7',
        'Kosta Rika' => '18',
        'Kuveyt' => '12',
        'Kuzey Makedonya' => '7',
        'Küba' => '18',
        'Kıbrıs Rum K.' => '7',
        'Kırgızistan' => '7',
        'Laos' => '19',
        'Latviya' => '7',
        'Lesotho' => '14',
        'Liberya' => '14',
        'Libya' => '13',
        'Lihtenştayn' => '1',
        'Litvanya' => '7',
        'Lübnan' => '12',
        'Lüksemburg' => '1',
        'Macaristan' => '6',
        'Madagaskar' => '14',
        'Makau' => '16',
        'Malavi' => '14',
        'Maldivler' => '19',
        'Malezya' => '15',
        'Mali' => '14',
        'Malta' => '4',
        'Maritius' => '14',
        'Marshall Adaları' => '18',
        'Martinik' => '18',
        'Mayotte Adaları' => '14',
        'Meksika' => '9',
        'Mikronezya' => '18',
        'Moldavya Cumhuriyeti' => '7',
        'Monako' => '1',
        'Montegero' => '7',
        'Montserrat' => '18',
        'Moritanya' => '14',
        'Mozambik' => '14',
        'Moğolistan' => '16',
        'Myanmar' => '19',
        'Mısır' => '12',
        'Nambiya' => '14',
        'Nauru Cumhuriyeti' => '19',
        'Nepal' => '19',
        'Nevis' => '18',
        'Nijer' => '14',
        'Nijerya' => '14',
        'Nikaragua' => '18',
        'Niue' => '19',
        'Norveç' => '2',
        'Orta Afrika Cumhuriyeti' => '13',
        'Pakistan' => '16',
        'Palau' => '18',
        'Panama' => '18',
        'Papua Yeni Gine' => '19',
        'Paraguay' => '18',
        'Peru' => '18',
        'Polonya' => '6', // Polanya
        'Portekiz' => '2',
        'Porto Riko' => '18',
        'Reunion Adası' => '14',
        'Romanya' => '6',
        'Ruanda' => '14',
        'Rusya' => '7',// Rusya Federasyonu
        'SAINT HELENA' => '10',
        'Saipan' => '18',
        'San Marino' => '1',
        'Sao Tome Ve Principe' => '14',
        'Senegal' => '14',
        'Seyşeller' => '14',
        'Sierra Leone' => '14',
        'Singapur' => '15',
        'Slovakya' => '7',
        'Slovenya' => '7',
        'Solomon Adaları' => '19',
        'Somali' => '14',
        'Somaliland Cumhuriyeti' => '14',
        'Sri Lanka' => '17',
        'St Barthelemy' => '18',
        'St Eustatius' => '18',
        'St Kitts' => '18',
        'St Lucia' => '18',
        'St Maarten' => '18',
        'St Vincent' => '18',
        'Sudan' => '13',
        'Surinam' => '18',
        'Suriye' => '12',
        'Suudi Arabistan' => '12',
        'Swaziland' => '14',
        'Sırbistan' => '7',
        'Tacikistan' => '7',
        'Tahiti' => '19',
        'Tanzanya' => '14',
        'Tayland' => '16',
        'Tayvan' => '15',
        'Togo' => '14',
        'Tonga' => '19',
        'Trinidad Ve Tobago' => '18',
        'Tunus' => '11',
        'Turkmenistan' => '7',
        'Tuvalu' => '19',
        'Turks Ve Caicos Adalari' => '18', // Türk Ve Kaikos Adaları
        'Uganda' => '14',
        'Ukrayna' => '5',
        'Umman' => '12',
        'Uruguay' => '18',
        'Vanuatu' => '19',
        'Vatikan' => '1',
        'Venezuela' => '18',
        'Vietnam' => '17',
        'Virjin Adaları(ABD)' => '18',
        'Virjin Adaları(UK)' => '18',
        'Yemen' => '13',
        'Yeni Kaledonya' => '19',
        'Yeni Zelanda' => '17',
        'Yunanistan' => '3',
        'Zambiya' => '14',
        'Zimbabve' => '14',
        'Çad' => '14',
        'Çekya' => '6', // Çek Cum.
        'Çin' => '16',// Çin Halk Cum.
        'Özbekistan' => '7',
        'Ürdün' => '12',
        'Birleşik Krallik' => '1', // İngiltere
        'İran' => '12',
        'İrlanda' => '1', // İrlanda Cum.
        'İspanya' => '2',
        'İsrail' => '7',
        'İsveç' => '2',
        'İsviçre' => '1',
        'İtalya' => '1',
        'İzlanda' => '7',
        'Şili' => '18'
    ];

    /**
     * Update zornes in country table;
     *
     * @return array
     */
    public function updateZones(): array
    {

        $notFound = [];
        foreach (\App\Models\LocationCountry::get() as $c) {
            $langs = json_decode($c->translations);
            if (isset($this->countryList[$langs->tr])) {
                $c->cargo_dhl_id = $this->countryList[$langs->tr];
                $c->save();
            } else {
                $notFound[] = $langs->tr;
            }
        }

        return $notFound;
    }
}
