<?php

namespace App\Libraries\Shippings\Zones\Items;

use App\Libraries\Shippings\Zones\zoneInterface;

class upsZones implements zoneInterface
{

    public $name = 'ups';

    protected $countryList = [
        'DE' => ['Almanya', '1'],
        'NL' => ['Hollanda', '1'],
        'HU' => ['Macaristan', '2'],
        'PL' => ['Polonya', '2'],
        'AT' => ['Avusturya', '2'],
        'BE' => ['Belçika', '2'],
        'GB' => ['İngiltere', '2'],
        'IE' => ['İrlanda Cumhuriyeti', '2'],
        'CH' => ['İsviçre', '2'],
        'LU' => ['Lüksemburg', '2'],
        'SI' => ['Slovenya', '2'],
        'UA' => ['Ukrayna', '2'],
        'FR' => ['Fransa', '3'],
        'ES' => ['İspanya', '3'],
        'IT' => ['İtalya', '3'],
        'GR' => ['Yunanistan', '3'],
        'AZ' => ['Azerbaycan', '3'],
        'CZ' => ['Çekya', '3'],
        'HR' => ['Hırvatistan', '3'],
        'ME' => ['Karadağ', '3'],
        'MT' => ['Malta', '3'],
        'PT' => ['Portekiz', '3'],
        'RO' => ['Romanya', '3'],
        'BH' => ['Bahreyn', '4'],
        'BY' => ['Belarus', '4'],
        'KZ' => ['Kazakistan', '4'],
        'CY' => ['Kıbrıs', '4'],
        'KG' => ['Kırgızistan', '4'],
        'KW' => ['Kuveyt', '4'],
        'LV' => ['Letonya', '4'],
        'LT' => ['Litvanya', '4'],
        'RS' => ['Sırbistan', '4'],
        'US' => ['Amerika Birleşik Devletleri ', '5'],
        'CA' => ['Kanada', '5'],
        'FO' => ['Faroe Adaları', '6'],
        'PH' => ['Filipinler', '6'],
        'GL' => ['Grönland', '6'],
        'LY' => ['Libya', '6'],
        'AU' => ['Avustralya', '7'],
        'MA' => ['Fas', '7'],
        'NG' => ['Nijerya', '7'],
        'BB' => ['Barbados', '8'],
        'BZ' => ['Belize', '8'],
        'DM' => ['Dominika', '8'],
        'GP' => ['Guadelup', '8'],
        'HT' => ['Haiti', '8'],
        'CL' => ['Şili', '8'],
        'FI' => ['Finlandiya', '9'],
        'SE' => ['İsveç', '9'],
        'BG' => ['Bulgaristan', '9'],
        'DK' => ['Danimarka', '9'],
        'GN' => ['Gine', '9'],
        'KM' => ['Komor', '9'],
        'CD' => ['Kongo Halk Cumhuriyeti', '9'],
        'MR' => ['Moritanya', '9'],
        'SN' => ['Senegal', '9'],
        'SK' => ['Slovak Cumhuriyeti', '10'],
        'MX' => ['Meksika', '10'],
        'AF' => ['Afganistan', '11'],
        'AE' => ['Birleşik Arap Emirlikleri', '11'],
        'KE' => ['Kenya', '11'],
        'LA' => ['Laos', '11'],
        'LB' => ['Lübnan', '11'],
        'MU' => ['Mauritius', '11'],
        'EG' => ['Mısır', '11'],
        'MZ' => ['Mozambik', '11'],
        'UZ' => ['Özbekistan', '11'],
        'RU' => ['Rusya (Posta Kodu 101000-453999 & 460000-619999)', '15'],
        'SL' => ['Sierra Leone', '11'],
        'SG' => ['Singapur', '11'],
        'TZ' => ['Tanzanya', '11'],
        'JO' => ['Ürdün', '11'],
        'ZW' => ['Zimbabve', '11'],
        'NO' => ['Norveç', '12'],
        'AL' => ['Arnavutluk', '12'],
        'BJ' => ['Benin', '12'],
        'BW' => ['Botsvana', '12'],
        'BF' => ['Burkina Faso', '12'],
        'BI' => ['Burundi', '12'],
        'ID' => ['Endonezya', '12'],
        'EE' => ['Estonya', '12'],
        'ZA' => ['Güney Afrika', '12'],
        'GE' => ['Gürcistan', '12'],
        'IL' => ['İsrail', '12'],
        'QA' => ['Katar', '12'],
        'PK' => ['Pakistan', '12'],
        'SA' => ['Suudi Arabistan', '12'],
        'AR' => ['Arjantin', '13'],
        'BD' => ['Bangladeş', '13'],
        'BA' => ['Bosna-Hersek', '13'],
        'DZ' => ['Cezayir', '13'],
        'DJ' => ['Cibuti', '13'],
        'EC' => ['Ekvator', '13'],
        'AM' => ['Ermenistan', '13'],
        'FJ' => ['Fiji Adası', '13'],
        'CI' => ['Fildişi Sahili', '13'],
        'GU' => ['Guam', '13'],
        'IN' => ['Hindistan', '13'],
        'IQ' => ['Irak', '13'],
        'JM' => ['Jamaika', '13'],
        'JP' => ['Japonya', '13'],
        'CO' => ['Kolombiya', '13'],
        'CR' => ['Kosta Rika', '13'],
        'MG' => ['Madagaskar', '13'],
        'MK' => ['Makedonya (FYROM)', '13'],
        'MW' => ['Malavi', '13'],
        'MY' => ['Malezya', '13'],
        'NE' => ['Nijer', '13'],
        'NI' => ['Nikaragua', '13'],
        'RW' => ['Ruanda', '13'],
        'LK' => ['Sri Lanka', '13'],
        'TH' => ['Tayland', '13'],
        'TW' => ['Tayvan', '13'],
        'TN' => ['Tunus', '13'],
        'UG' => ['Uganda', '13'],
        'NZ' => ['Yeni Zelanda', '13'],
        'BO' => ['Bolivya', '14'],
        'BR' => ['Brezilya', '14'],
        'BN' => ['Brunei Darusselam', '14'],
        'TD' => ['Çad', '14'],
        'CN' => ['Çin Halk Cumhuriyeti', '14'],
        'DO' => ['Dominik Cumhuriyeti', '14'],
        'SV' => ['El Salvador', '14'],
        'ET' => ['Etiyopya', '14'],
        'GF' => ['Fransız Guyanası', '14'],
        'GA' => ['Gabon', '14'],
        'GM' => ['Gambiya', '14'],
        'GH' => ['Gana', '14'],
        'GT' => ['Guatemala', '14'],
        'HK' => ['Hong Kong', '14'],
        'IS' => ['İzlanda', '14'],
        'JE' => ['Jersey', '14'],
        'CM' => ['Kamerun', '14'],
        'KR' => ['Kore, Güney', '14'],
        'KV' => ['Kosova ', '14'],
        'LR' => ['Liberya', '14'],
        'MV' => ['Maldiv Adaları', '14'],
        'ML' => ['Mali', '14'],
        'MN' => ['Moğolistan', '14'],
        'MD' => ['Moldova', '14'],
        'NA' => ['Namibya', '14'],
        'PA' => ['Panama', '14'],
        'PY' => ['Paraguay', '14'],
        'PE' => ['Peru', '14'],
        'SC' => ['Seyşeller', '14'],
        'SR' => ['Surinam', '14'],
        'TG' => ['Togo', '14'],
        'TT' => ['Trinidad ve Tobago', '14'],
        'OM' => ['Umman', '14'],
        'VE' => ['Venezuela', '14'],
        'VN' => ['Vietnam', '14'],
        'NC' => ['Yeni Kaledonya', '14'],
        'ZM' => ['Zambiya', '14'],
        'AO' => ['Angola', '15'],
        'AG' => ['Antigua ve Barbuda', '15'],
        'AW' => ['Aruba', '15'],
        'BS' => ['Bahamalar', '15'],
        'BM' => ['Bermuda', '15'],
        'KY' => ['Cayman Adaları', '15'],
        'GI' => ['Cebelitarık', '15'],
        'PF' => ['Fransız Polinezyası', '15'],
        'HN' => ['Honduras', '15'],
        'KH' => ['Kamboçya', '15'],
        'CG' => ['Kongo', '15'],
        'MO' => ['Makao', '15'],
        'NP' => ['Nepal', '15'],
        'PG' => ['Papua Yeni Gine', '15'],
        'RE' => ['Reunion', '15'],
        'UY' => ['Uruguay', '15'],
        'VI' => ['Virgin Adaları ABD', '15'],
        'AS' => ['Amerika Samoası', '15'],
        'AD' => ['Andorra', '15'],
        'AI' => ['Angila', '15'],
        'PS' => ['Batı Şeria (Gaza)', '15'],
        'BT' => ['Butan', '15'],
        'AN' => ['Bonaire', '15'],
        'BQ' => ['Bonaire', '15'],
        'CV' => ['Cape Verde Adaları', '15'],
        'ES2' => ['Ceuta', '15'],
        'CK' => ['Cook Adaları', '15'],
        'CW' => ['Curaçao', '15'],
        'TL' => ['Doğu Timor', '15'],
        'GQ' => ['Ekvator Ginesi', '15'],
        'ER' => ['Eritre', '15'],
        'GB4' => ['Galler', '2'],
        'GW' => ['Gine-Bissau', '15'],
        'GD' => ['Grenada', '15'],
        'GG' => ['Guernsey', '15'],
        'GY' => ['Guyana', '15'],
        'VG' => ['İngiliz Virgin Adaları', '15'],
        'GB0' => ['İngiltere', '2'],
        'GB1' => ['İngiltere', '2'],
        'GB3' => ['İskoçya', '2'],
        'ES1' => ['Kanarya Adaları', '15'],
        'IC' => ['Kanarya Adaları', '15'],
        'KI' => ['Kiribati', '15'],
        'GB2' => ['Kuzey İrlanda', '2'],
        'MP' => ['Kuzey Mariana Adaları', '15'],
        'LS' => ['Lesoto', '15'],
        'LI' => ['Lihtenştayn', '15'],
        'MH' => ['Marshall Adaları', '15'],
        'MQ' => ['Martinik', '15'],
        'YT' => ['Mayotte', '15'],
        'ES3' => ['Melilla', '15'],
        'FM' => ['Mikronezya(Federal Devletleri)', '15'],
        'MC' => ['Monako', '15'],
        'MS' => ['Montserrat', '15'],
        'MM' => ['Myanmar', '15'],
        'KN' => ['Nevis(St . Kitts)', '15'],
        'CF' => ['Orta Afrika Cumhuriyeti', '15'],
        'PW' => ['Palau', '15'],
        'PR' => ['Porto Riko', '15'],
        'RU1' => ['Rusya(Posta Kodu - Diğer)', '15'],
        'RU0' => ['Rusya(Posta Kodu 101000 - 453999 & 460000 - 619999)', '15'],
        'AN3' => ['Saba', '15'],
        'WS' => ['Samoa', '15'],
        'SM' => ['San Marino', '15'],
        'ST' => ['Sao Tome', '15'],
        'SB' => ['Solomon Adaları', '15'],
        'BL' => ['St . Barthelemy', '15'],
        'AN4' => ['St . Eustatius', '15'],
        'LC' => ['St . Luçia', '15'],
        'SX' => ['St . Maarten', '15'],
        'VC' => ['St . Vincent ve Grenadines', '15'],
        'SZ' => ['Svaziland', '15'],
        'TJ' => ['Tacikistan', '15'],
        'TO' => ['Tonga', '15'],
        'TC' => ['Turks ve Caicos Adaları', '15'],
        'TV' => ['Tuvalu', '15'],
        'TM' => ['Türkmenistan', '15'],
        'VU' => ['Vanuatu', '15'],
        'WF' => ['Wallis ve Futuna Adaları', '15'],
        'YE' => ['Yemen Cumhuriyeti', '15']];

    /**
     * @return array
     */
    public function updateZones(): array
    {
        $notFound = [];
        foreach (\App\Models\LocationCountry::get() as $c) {

            if (isset($this->countryList[$c->iso2])) {
                $c->cargo_ups_id = $this->countryList[$c->iso2][1];
                $c->save();
            } else {
                $notFound[] = $c->iso2;
            }
        }

        return $notFound;
    }
}
